service: auth-server

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  timeout: 30 

  environment:
    CLIENT_ID: ${file(config.json):CLIENT_ID}
    CLIENT_SECRET: ${file(config.json):CLIENT_SECRET}
    CALENDAR_ID: ${file(config.json):CALENDAR_ID}

functions:
  getAuthURL:
    handler: handler.getAuthURL
    events:
      - http:
          path: api/get-auth-url
          method: get
          cors:
            origin: 'https://meet-ten-gamma.vercel.app'
            headers:
              - Content-Type
              - Authorization
            allowCredentials: false

  getAccessToken:
    handler: handler.getAccessToken
    events:
      - http:
          path: api/token/{code}
          method: get
          cors:
            origin: 'https://meet-ten-gamma.vercel.app'
            headers:
              - Content-Type
              - Authorization
            allowCredentials: false

  getCalendarEvents:
    handler: handler.getCalendarEvents
    events:
      - http:
          path: api/get-events/{access_token}
          method: get
          cors:
            origin: 'https://meet-ten-gamma.vercel.app'
            headers:
              - Content-Type
              - Authorization
            allowCredentials: false
